# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Moreno
email: moreno.ryanr@gmail.com
description: >
  Ryan Moreno is a Ph.D. student at the University of Wisconsin-Madison
  studying theoretical computer science.
footerdescription: Computer Science Ph.D. Student
footerdescriptiontwo: University of Wisconsin-Madison
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryan-moreno.github.io" # the base hostname & protocol for your site
linkedin_username: "ryan-moreno-37bb96127"
github_username:  "ryan-moreno"
email_username: moreno.ryanr@gmail.com

# Build settings
markdown: kramdown
