# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Moreno
email: moreno.ryanr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Moreno is an undergraduate student at the University of Southern California studying
  Computer Science and Creative Writing.
footerdescription: >-
  Computer Science and Creative Writing major
  University of Southern California
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryan-moreno.github.io" # the base hostname & protocol for your site
linkedin_username: "ryan-moreno-37bb96127"
github_username:  "ryan-moreno"
email_username: moreno.ryanr@gmail.com

# Build settings
markdown: kramdown
